### ISSUE TITLE
Bugfix 2.0.x Archim2 Full graphic LCD

### ISSUE THREAD

**Issue by Allted** [ultimachine/Marlin#2]
First off, thank you for getting this working with 2.0! I only want to have to support one branch of firmware for my builds and I have most of them already moved over to 2.0 so when this is solid this will be much easier for me. I hope the changes get pushed/merged soon. 

I use a lot of the Full graphic LCD's,
`#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`
The firmware will compile but the screen only shows nonsense. The screen screen and my library's have been verified on a few other boards.

I had the same issue with the first Archim board as I am having with the Archim2.

I poked around but I think this issue is over my head but if you are busy maybe you could point me at where to look?

**Comment by tonokip** [comment]
fixed here: https://github.com/ultimachine/Marlin/commit/095f6c7e522ec588364cab3569806f16ec907d4c

credit goes to marcio at lulzbot for finding optimized timings.

**Comment by Allted** [comment]
I think that is set up for another display I commented that display out, enabled the screen above and it doesn't compile a few errors. 
I will look into changing the speed setting I tried a few things on the current bugfix 2.0.x and it didn't work with the screen but I haven't given up yet.
Thanks for the update.
