### ISSUE TITLE
class TMC2130Stepper has no member named 'hysterisis_low'

### ISSUE THREAD

**Issue by Camble** [ultimachine/Marlin#3]
Trying to compile the marlin-1.1.5-einsy0.5c branch using the TMC2130 Stepper library v2.2.1 and get the following error:

sketch\stepper_indirection.cpp: In function 'void tmc2130_init(TMC2130Stepper&, uint16_t, uint32_t, const float&)':
stepper_indirection.cpp:184: error: 'class TMC2130Stepper' has no member named 'hysterisis_low'
     st.hysterisis_low(1); // HEND = -2
        ^
exit status 1
'class TMC2130Stepper' has no member named 'hysterisis_low'

**Comment by PatrikTheDev** [comment]
I have this problem too

**Comment by tonokip** [comment]
changed to hysterisis_end
0acc4e8
